### ISSUE TITLE
Erro de Certificado inválido ao consumir API com aplicação publicada na AWS (EBS)

### ISSUE THREAD

**Issue by rodrigoqb** [edumucelli/cepaberto-api-examples#24]
Boa noite!

Realizei a implementação do consumo da API do Cep Aberto na minha aplicação .NET 5, e rodando local está tudo 100%, consigo passar o CEP e recuperar Latitude e Longitude. Porém, quando publico minha aplicação na AWS (EBS) estou tendo o seguinte retorno no meu serviço que consome a API do Cep Aberto:

`Message: The SSL connection could not be established, see inner exception. - Exception: System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid`

Lembrando que, estou informando no Header o Token gerado após cadastro na plataforma, e localmente não tenho problemas.

Segue log completo da exception retornada:

`Message: The SSL connection could not be established, see inner exception. - Exception: System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) - StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)`
   
   A URL a ser consumida está sendo montada da seguinte maneira:
   
   `var apiUrl = $"{apiBaseUrl}{apiVersion}/cep?cep={zipCode}";`

Onde:

- apiBaseUrl = https://www.cepaberto.com/api/
- apiVersion = v3

O Certificado da minha aplicação está válido até Maio desse ano, emitido pela ACM.

Poderia me ajudar a identificar o motivo de não conseguir consumir nesse cenário descrito, por gentileza?

Obrigado desde já!

**Comment by edumucelli** [comment]
Interessante, pois o certificado do CEPAberto (Let's Encrypt) está valido pelo menos até Abril, você pode conferir por si mesmo.

**Comment by rodrigoqb** [comment]
> Interessante, pois o certificado do CEPAberto (Let's Encrypt) está valido pelo menos até Abril, você pode conferir por si mesmo.

Exatamente, e temos esse comportamento somente quando publicado na AWS. Acredito que se, de fato, fosse algo relacionado ao certificado nem localmente eu conseguiria consumir a API de vocês.

Já teve relato de algum cenário parecido com esse, @edumucelli ? Tem ideia de como podemos sair do outro lado com esse item?

**Comment by edumucelli** [comment]
Nunca tive relato desse erro, veja [esse](https://kudzia.eu/b/2021/12/net-core-under-linux-throws-the-remote-certificate-is-invalid-because-of-errors-in-the-certificate-chain-nottimevalid-when-communicating-with-https-server-having-letsencrypt-cert/) post, acredito que possa te dar uma indicação.
